- name: Cleanup docker hosts
  hosts: docker_hosts
  become: false
  tasks:
    - name: "Remove orphans"
      community.docker.docker_compose_v2:
        project_src: ./docker
        pull: never
        remove_orphans: true
    - name: "Prune system"
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
