- name: Update packages
  hosts: all
  become: true
  tasks:
    - name: "Update packages"
      ansible.builtin.package:
        update_cache: true
        upgrade: true

- name: Update containers
  hosts: docker_hosts
  become: false
  tasks:
    - name: "Update docker containers"
      community.docker.docker_compose_v2:
        project_src: ./docker
        pull: always
