- name: Update all running hosts
  hosts: all:!status_stopped:!role_homeassistant
  become: false
  vars:
    # Support environment variable override for CI/CD environments (e.g., Semaphore)
    # Local development uses vault encryption; CI/CD uses PROXMOX_API_TOKEN env var
    # Use environment variable if set, otherwise fall back to vault-encrypted value
    proxmox_api_token: "{{ lookup('env', 'PROXMOX_API_TOKEN') | default(vault_proxmox_api_token, true) }}"
    vault_proxmox_api_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35643763633638323066353939393265366131333030363438383435343163616239653233303636
      3461346162623763373466653736643564613065383865660a346461343238393362323239333735
      63306131363865613765313537353465383630303566653738653764373738646131356463393364
      6364306161373239370a306461316262616333633934313435643666333930666637653339303839
      37366135356137393663643330623535663136636662353730363066666266316366383532336435
      6231366264326533656433613732653438363239313237383235
  pre_tasks:
    - name: "Create pre-update snapshot for Proxmox VMs/LXCs"
      when: proxmox_vmid is defined
      community.general.proxmox_snap:
        api_host: "proxmox1.home.willem.vooijs.eu"
        api_user: ansible@pve
        api_token_id: ansible
        api_token_secret: "{{ proxmox_api_token }}"
        validate_certs: false
        vmid: "{{ proxmox_vmid }}"
        state: present
        snapname: "pre-update-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
        description: "Pre-update snapshot created by Ansible on {{ ansible_date_time.iso8601 }}"
        retention: 3
      ignore_errors: true
      register: snapshot_result
      delegate_to: localhost
  tasks:
    - name: "Update system packages"
      when: snapshot_result is succeeded or proxmox_vmid is not defined
      block:
        - name: "Update Linux packages"
          when: ansible_system == "Linux"
          block:
            - name: "Update packages"
              ansible.builtin.package:
                update_cache: true
                upgrade: true
              become: true
            - name: "Check if reboot required"
              ansible.builtin.stat:
                path: /var/run/reboot-required
              register: reboot_required

        - name: "Update macOS packages"
          when: ansible_system == "Darwin"
          block:
            - name: "Update Homebrew packages"
              community.general.homebrew:
                update_homebrew: true
                upgrade_all: true
            - name: "Update Homebrew casks"
              community.general.homebrew_cask:
                upgrade_all: true

    - name: "Update Docker containers"
      when: inventory_hostname in groups['role_docker']
      block:
        - name: "Pull and start containers"
          community.docker.docker_compose_v2:
            project_src: ./docker
            pull: always
  post_tasks:
    - name: "Cleanup Docker"
      when: inventory_hostname in groups['role_docker']
      block:
        - name: "Remove orphans"
          community.docker.docker_compose_v2:
            project_src: ./docker
            pull: never
            remove_orphans: true
        - name: "Prune system"
          community.docker.docker_prune:
            containers: true
            images: true
            networks: true
            volumes: true
            builder_cache: true
