- name: Update all running hosts
  hosts: all:!status_stopped:!role_homeassistant
  become: false
  vars:
    # Proxmox API token from PROXMOX_API_TOKEN environment variable
    # Local: source load_proxmox_token.sh to set the env var
    # Semaphore: set PROXMOX_API_TOKEN as environment variable in task
    proxmox_api_token: "{{ lookup('env', 'PROXMOX_API_TOKEN') }}"
  pre_tasks:
    - name: "Install Python dependencies for Proxmox modules"
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        state: present
      become: false
      delegate_to: localhost
      run_once: true

    - name: "Create pre-update snapshot for Proxmox VMs/LXCs"
      when: proxmox_vmid is defined
      community.proxmox.proxmox_snap:
        api_host: "proxmox1.home.willem.vooijs.eu"
        api_user: ansible@pve
        api_token_id: ansible
        api_token_secret: "{{ proxmox_api_token }}"
        validate_certs: false
        vmid: "{{ proxmox_vmid }}"
        state: present
        snapname: "pre-update-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
        description: "Pre-update snapshot created by Ansible on {{ ansible_date_time.iso8601 }}"
        retention: 3
      ignore_errors: true
      register: snapshot_result
      delegate_to: localhost
  tasks:
    - name: "Update system packages"
      when: snapshot_result is succeeded or proxmox_vmid is not defined
      block:
        - name: "Update Linux packages"
          when: ansible_system == "Linux"
          block:
            - name: "Update packages"
              ansible.builtin.package:
                update_cache: true
                upgrade: true
              become: true
            - name: "Check if reboot required"
              ansible.builtin.stat:
                path: /var/run/reboot-required
              register: reboot_required

        - name: "Update macOS packages"
          when: ansible_system == "Darwin"
          block:
            - name: "Update Homebrew packages"
              community.general.homebrew:
                update_homebrew: true
                upgrade_all: true
            - name: "Update Homebrew casks"
              community.general.homebrew_cask:
                upgrade_all: true

    - name: "Update Docker containers"
      when: inventory_hostname in groups['role_docker']
      block:
        - name: "Pull and start containers"
          community.docker.docker_compose_v2:
            project_src: ./docker
            pull: always
  post_tasks:
    - name: "Cleanup Docker"
      when: inventory_hostname in groups['role_docker']
      block:
        - name: "Remove orphans"
          community.docker.docker_compose_v2:
            project_src: ./docker
            pull: never
            remove_orphans: true
        - name: "Prune system"
          community.docker.docker_prune:
            containers: true
            images: true
            networks: true
            volumes: true
            builder_cache: true
