plugin: community.proxmox.proxmox
url: https://proxmox1.home.willem.vooijs.eu:8006
validate_certs: false
user: ansible@pve
token_id: ansible
# Token secret loaded from PROXMOX_API_TOKEN environment variable
# Local: source load_proxmox_token.sh to set the env var
# Semaphore: set PROXMOX_API_TOKEN as environment variable in task
token_secret: "{{ lookup('env', 'PROXMOX_API_TOKEN') }}"

# Enable to gather VM/LXC configuration facts
want_facts: true

# Compose dynamic host variables
compose:
  # Use the first IP address found in network configuration
  # Extract address from ipconfig0 or fall back to net0, then parse with ipaddr
  ansible_host: |
    {%- set ip = proxmox_ipconfig0.ip | default(proxmox_net0.ip) -%}
    {%- if ip -%}
      {%- set parsed = ip | ansible.utils.ipaddr('address') -%}
      {%- if parsed -%}{{ parsed }}{%- else -%}{{ ip.split('/')[0] }}{%- endif -%}
    {%- endif -%}
  # Override remote user for specific VMs
  ansible_user: |
    {%- if inventory_hostname == 'homeassistant' -%}
    root
    {%- else -%}
    willem
    {%- endif -%}

# Group VMs by their status and roles
keyed_groups:
  - key: proxmox_status
    prefix: status
  - key: proxmox_type
    prefix: type
  - key: proxmox_node
    prefix: node
  # Group by individual tags (roles)
  - key: proxmox_tags_parsed | default([])
    prefix: role
    separator: "_"

# Show all VMs/containers (remove status filter)
# filters:
#   - proxmox_status == "running"
